/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'app.view.MainViewViewModel',
        'app.view.MainViewViewController',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.tab.Panel'
    ],

    controller: 'mainview',
    viewModel: {
        type: 'mainview'
    },
    itemId: 'mainView',
    layout: 'border',

    items: [
        {
            xtype: 'toolbar',
            region: 'north',
            height: 30,
            itemId: 'TopToolBar',
            items: [
                {
                    xtype: 'button',
                    itemId: 'btnNewWindow',
                    text: 'New Window',
                    listeners: {
                        click: 'onBtnNewWindowClick'
                    }
                },
                {
                    xtype: 'button',
                    itemId: 'btnQuery',
                    text: 'Query',
                    listeners: {
                        click: 'onBtnQueryClick'
                    }
                }
            ]
        },
        {
            xtype: 'tabpanel',
            region: 'center',
            id: 'sqlTabPanel',
            itemId: 'SqlTabPanel',
            constrainHeader: true,
            header: false,
            removePanelHeader: false
        }
    ]

});